app = "ecoride-test"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile" # ou supprime cette ligne si tu utilises Node sans Docker

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]  # ← ⚠️ Ajoute bien cette ligne pour activer HTTPS
